image: maven:3.3.9-jdk-8

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository

deploy:jdk8:
  stage: deploy
  script:
    - mvn clean install
    - mvn $MAVEN_CLI_OPTS deploy
  only:
    - master
