# -----------        General Stuff        ------------
DatabaseType: SQLite
MySQL:
  Hostname: localhost
  Port: 3306
  Database: minecraft
  User: root
  Password: passy
disabled-worlds:
  world_nether
  world_the_end
language: en
# -----------        Cost Stuff        ------------
# this formula uses limited growth. Cost will raise and raise until it reaches a certain point
# Formula: maxCost - ( maxCost - minCost ) * multiplier ^ amountOfOwnedLands
# you can play around with the formula here: https://www.geogebra.org/m/S6uSGV7c
Formula:
  maxCost: 3000.0
  minCost: 500.0
  multiplier: 0.95
# on unclaim, this percentage of the original price is paid back.
Payback: 0.8