# -----------        General Stuff        ------------
DatabaseType: SQLite
MySQL:
  Hostname: localhost
  Port: 3306
  Database: minecraft
  User: root
  Password: passy
disabled-worlds:
  world_nether
  world_the_end
language: en
HelpCommandPerSite: 10
# -----------        Cost Stuff        ------------
# this formula uses limited growth. Cost will raise and raise until it reaches a certain point
# Formula: maxCost - ( maxCost - minCost ) * multiplier ^ amountOfOwnedLands
# you can play around with the formula here: https://www.geogebra.org/m/S6uSGV7c
Formula:
  maxCost: 3000.0
  minCost: 500.0
  multiplier: 0.95
# on unclaim, this percentage of the original price is paid back.
Payback: 0.8
Freelands: 1
ResetCost: 1000.0
# here you can manage your claims shop.
# - ClaimsQuantity:Price
# e.g. 10:5000
# which means, an user can buy 10 additional claims for 5000 dollars
Shop:
# set this to false, if you want to use the traditional permission based system
  enable: true
  extras:
    - PAPER:10:5000.0
    - PAPER:20:9000.0
    - PAPER:30:13500.0
    - PAPER:50:45000.0

# These are hard caps. If a player has the permission "landlord.limit.10" he will be able to buy up to 20 lands, but cant buy more claims than that.
limits:
  - 10
  - 20
  - 30
  - 40

# -----------        Map Stuff        ------------
Map:
  enable: true
# Refreshrate in Ticks. 20 ticks is equal to one seocnd. The lower you set the value the more laggy it might be
  LandMapRefreshRate: 10
