# -----------        General Stuff        -----------
# Available: SQLite / MySQL
DatabaseType: SQLite
MySQL:
  Hostname: localhost
  Port: 3306
  Database: minecraft
  User: root
  Password: passy

disabled-worlds:
  - world_nether
  - world_the_end

language: en

HelpCommandPerSite: 10

# -----------        Cost Stuff        ------------
# this formula uses limited growth. Cost will raise and raise until it reaches a certain point
# Formula: maxCost - ( maxCost - minCost ) * multiplier ^ amountOfOwnedLands
# you can play around with the formula here: https://www.geogebra.org/m/S6uSGV7c
Economy:
  enable: true

Formula:
  maxCost: 3000.0
  minCost: 500.0
  multiplier: 0.95

# on unclaim, this percentage of the original price is paid back.
Payback: 0.8
Freelands: 1
ResetCost: 1000.0

# here you can manage your claims shop.
# - ClaimsQuantity:Price
# e.g. 10:5000
# which means, an user can buy 10 additional claims for 5000 dollars
Shop:
# set this to false, if you want to use the traditional permission based system
  enable: true
  extras:
    - PAPER:10:5000.0
    - PAPER:20:9000.0
    - PAPER:30:13500.0
    - PAPER:50:45000.0

# These are hard caps. If a player has the permission "landlord.limit.10" he will be able to buy up to 20 lands, but cant buy more claims than that.
limits:
  - 10
  - 20
  - 30
  - 40

Homes:
  enable: true
  spawnParticles: true
  teleportCost: 100.0
  delay: 3

# Where should the "Entering XXX's land" be displayed? Available are ActionBar, Chat, Disabled
LandMessage: ActionBar

# -----------        Map Stuff        ------------
Map:
  enable: true
# Refreshrate in Ticks. 20 ticks is equal to one second. The lower you set the value the more laggy it might be
  refreshRate: 10

Borders:
  # show the chunkborders with particles
  enable: false
  # interval in seconds
  refreshRate: 10

CommandSettings:
  ListLands:
    enable: true
# gui or chat
    mode: gui
# How many lands should be displayed per page?
    landsPerPage: 15


# define your default flags here. Every flag will be manageable in ll manage
# Construction of a new Flag:
# flag defaultState:toggleableState
# You can also set specific groups: e.g. interact allow all:deny nonmembers
# this allows toggling the flagstate between allowing interaction for everyone and just allow oweners and members
# if you are adding a new flag, you must implement the necessary strings in the language file! Just copy paste it from an existing flag.
Flags:
  - 'interact allow all:deny nonmembers'
  - 'chest-access deny nonmembers:allow all'
  - 'creeper-explosion deny all:allow all'
  - 'pvp deny all:allow all'
  - 'build deny nonmembers:allow all'

MaItem:
  enabled: true
  item: STICK
# define your modes of operation here.
# Syntax: clickaction:condition:whatshouldhappen
# Available actions:
# - leftclickblock, leftclickair, shiftleftclickblock, shiftleftclickair (same for right obv)
# Available conditions:
# - ownland, otherland, anyland
# Available whatshouldhappen:
# - info, buy, manage, manageall, togglemap, toggleborders
  modes:
    - 'rightclickblock:anyland:info'
    - 'leftclickblock:anyland:buy'
    - 'shiftrightclickblock:ownland:manage'
    - 'shiftleftclickblock:ownland:manageall'
    - 'rightclickair:anyland:togglemap'
    - 'leftclickair:anyland:toggleborders'

# These options will be manageable in ll manage
Manage:
  friends:
    enable: true
  regenerate:
    enable: true
    item: BARRIER
  setgreet:
    enable: true
    item: BAKED_POTATO
  setfarewell:
    enable: true
    item: CARROT_ITEM
  unclaim:
    enable: true
    item: BLAZE_POWDER
  build:
    enable: true
    item: GRASS
  interact:
    enable: true
    item: STONE_BUTTON
  chest-access:
    enable: true
    item: CHEST
  creeper-explosion:
    enable: true
    item: TNT
  pvp:
    enable: true
    item: DIAMOND_SWORD
  mob-spawning:
    enable: true
    item: MONSTER_EGG
# If you dont want your users to manage a specific mobspawn, just comment out the line with #
    toggleableMobs:
      - ELDER_GUARDIAN
      - WITHER_SKELETON
      - STRAY
      - HUSK
      - ZOMBIE_VILLAGER
      - SKELETON_HORSE
      - ZOMBIE_HORSE
      - ARMOR_STAND
      - DONKEY
      - MULE
      - EVOKER
      - VEX
      - VINDICATOR
      - ILLUSIONER
      - CREEPER
      - SKELETON
      - SPIDER
      - GIANT
      - ZOMBIE
      - SLIME
      - GHAST
      - PIG_ZOMBIE
      - ENDERMAN
      - CAVE_SPIDER
      - SILVERFISH
      - BLAZE
      - MAGMA_CUBE
      - ENDER_DRAGON
      - WITHER
      - BAT
      - WITCH
      - ENDERMITE
      - GUARDIAN
      - SHULKER
      - PIG
      - SHEEP
      - COW
      - CHICKEN
      - SQUID
      - WOLF
      - MUSHROOM_COW
      - SNOWMAN
      - OCELOT
      - IRON_GOLEM
      - HORSE
      - RABBIT
      - POLAR_BEAR
      - LLAMA
      - PARROT
      - VILLAGER

version: 9